Avoid gcc4.x errors on strict aliasing
From f4e6337d2101da685bc07b0e87cae8ef7c015c95 Mon Sep 17 00:00:00 2001
Message-Id: <f4e6337d2101da685bc07b0e87cae8ef7c015c95.1300329492.git.linda.knippers@hp.com>
In-Reply-To: <cover.1300329492.git.linda.knippers@hp.com>
References: <cover.1300329492.git.linda.knippers@hp.com>
From: Linda Knippers <linda.knippers@hp.com>
Date: Wed, 16 Mar 2011 22:18:22 -0400
Subject: [PATCH 2/4] Avoid gcc4.x errors on strict aliasing
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

The network test helper commands (at least do_accept.c) generate
gcc4.x errors:
do_accept.c:47: error: dereferencing pointer ‘sock_addr4’ does break
strict-aliasing rules
do_accept.c:30: note: initialized from here
do_accept.c:50: error: dereferencing pointer ‘sock_addr6’ does break
strict-aliasing rules
do_accept.c:31: note: initialized from here

Turned off the error checking for now since this is pretty
standard socket code.

Also added a missing rpm dependency.

Signed-off-by: Linda Knippers <linda.knippers@hp.com>